include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: ignore
    avoid_function_literals_in_foreach_calls: ignore
    use_build_context_synchronously: ignore
    invalid_use_of_visible_for_testing_member: ignore
    
